---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seeker.
--- DateTime: 2020/7/1 12:06
---
ngx.req.get_body()
local data = ngx.req.get_body_data()
print(ngx.md5(data.."*&^%$#$^&kjtrKUYG"))