---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seeker.
--- DateTime: 2020/6/30 19:16
---
local res = ngx.location.capture(
        "/get/print_param",
        {
            --URI 内容传递过程中是需要调用 ngx.encode_args 进行规则转义
            method = ngx.HTTP_POST,
            args = ngx.encode_args({a=1,b='2&'}),
            body = ngx.encode_args({c=3,d='5&'})
--[[            否则得这样写
            args = 'a=1&b=2%26',  -- 注意这里的 %26 ,代表的是 & 字符
            body = 'c=3&d=4%26']]
        }
)
ngx.say('body')
ngx.say(res.body)