---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seeker.
--- DateTime: 2020/7/1 11:56
---

-- 读取请求体，默认不加载请求体
ngx.req.read_body()
local args,err = ngx.req.get_uri_args()

--① 引用 resty.http 库资源
local http = require "resty.http"
local httpc =http.new()
local res,err = httpc:request_uir(
        "http://localhost:81/spe_md5",
        {
            method = "POST",
            body = args.data,
        }
)
if 200 ~= res.status then
    ngx.exit(res.status)
end

if args.key == res.body then
    ngx.say("valid request")
else
    ngx.say("invalid request")
end