---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by seeker.
--- DateTime: 2020/6/30 17:01
---
local res = ngx.location.capture(
        "/sum",{args={a=3,b=9}}
)
ngx.say("status:",res.status,"response:",res.body)